# Generated by Django 5.0.1 on 2024-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='TipoDeporte',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('nombre', models.CharField(max_length=50)),
        ('descripcion', models.TextField()),
        ('estado', models.CharField(default='A', max_length=1)),
      ],
      options={
        'verbose_name': 'Tipo de Deporte',
        'verbose_name_plural': 'Tipos de Deportes',
        'ordering': ['id'],
      },
    ),
  ]
