# Generated by Django 5.0.1 on 2024-01-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
